### ISSUE TITLE
New version of run-once script with the same name?

### ISSUE THREAD

**Issue by MiqViq** [chilcote/outset#10]
When pushing new versions of run-once scripts to clients will they be run if the script name (and path) stays the same?
What about checksumming the run-once script and writing it to run-prefs?
Then if checksum of the specific script name does not match to the previous record the script will be run once again.
I have to admit that I have not tested current version of outset in any way yet...

**Comment by chilcote** [comment]
I'll think about it and will whip something up when I have time. It kind of goes against the concept of "run-once" though. Another counter intuitive option would be to put your script in login-every and then have the script delete itself upon completion.

**Comment by MiqViq** [comment]
Thanks for your speedy response.

I have used scriptRunner previously and with that the solution was to save the new version of the script with new name like runoncetask-2015-03-31.sh.

I guess that the plist could look like this:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>/Library/Management/Scripts/once/runoncetask1.sh</key>
	<dict>
		<key>MD5</key>
		<string>1511d66b4f6904810e010ef6c715b560</string>
		<key>TIMESTAMP</key>
		<string>2015-04-10</string>
	</dict>
	<key>/Library/Management/Scripts/once/runoncetask2.sh</key>
	<dict>
		<key>MD5</key>
		<string>2511d66b4f6904810e010ef6c715b565</string>
		<key>TIMESTAMP</key>
		<string>2015-04-22</string>
	</dict>
</dict>
</plist>

And the logic for checking could be:

1) check if the script path exists in plist 
2) if it does then get it's dictionary and check for the run date > if not then run it
3) if run date exists then verify md5 for script path > if differs then run it

**Comment by erikng** [comment]
Mager, I have a solution for this with regards to moving them to every-login. I can send you an example.

**Comment by grahamgilbert** [comment]
I'd vote for keeping the functionality the same as it is now. Let's say I'm setting up a default dock - if I update that, im going to get some pissed users when I blat their dock.

**Comment by chilcote** [comment]
Agreed.  I think using login-every with idempotence is the way to go.
