### ISSUE TITLE
FR: Sign Outset binary

### ISSUE THREAD

**Issue by jmahlman** [chilcote/outset#107]
With the upcoming changes to macOS Ventura login items asking if the outset binary can be signed in releases.
I understand that signing the binary is a simple process but for those that cannot do it for whatever reason would really benefit from this.

**Comment by gregneagle** [comment]
Outset is not a _binary_.
Outset is a Python script, which complicates the whole signing bit.
You do not need to sign Outset in order for it to work in Ventura.
Let's say it was somehow signed, though. Who would sign it? I doubt Joe would want to use his personal signing identity.
Will you users not ask questions about a "Login Item" from "Joseph Chilcote"?

**Comment by Avatharian** [comment]
A helpful answer that could do with less snark. Greg you could literally save yourself (and others!) some time and typing by being less of an asshole sometimes. the first and 3rd sentence were anough.

**Comment by jmahlman** [comment]
Excuse me for using the incorrect term but you **can** still sign a script. However, I do totally understand the idea of not wanting to sign with personal identity (though, plenty of others do this). I am also not saying it needs to be signed to work on Ventura, but thanks for the clarification, Greg.

Also, for some reason it didn't dawn on me right away but I realize that adding a different rule type of Label will work.

**Comment by gregneagle** [comment]
I may be an asshole, but I'm also right here. It's much much harder to usefully/successfully/functionally sign a script so that it actually passes the security checks. Compiled binaries are much easier in this regard. I thought it important to point out the difficulty and perhaps let Joe off the hook for a difficult request for his freely offered software.
