### ISSUE TITLE
Move to FoundationPlist

### ISSUE THREAD

**Issue by grahamgilbert** [chilcote/outset#12]
How do you feel about moving the plist handling over to FoundationPlist? It would save on problems like: https://twitter.com/clburlison/status/610870689545986048

Happy to do the work myself, but don't want to start if you're not keen on the idea.

**Comment by chilcote** [comment]
I would merge said pull request.

**Comment by grahamgilbert** [comment]
Appreciate you doing the work I promised to do, but could I trouble you for a release so AutoPkg can pull in your stellar work?

THANKS!

**Comment by chilcote** [comment]
Yes, I'll do a 1.0.1 release for this.

**Comment by grahamgilbert** [comment]
![Giphy](http://media1.giphy.com/media/nU704Y2jeFOHm/giphy.gif)

**Comment by chilcote** [comment]
I'd like to have at least one other person verify that I break anything.  Can you try this out and let me know if it works, please? (with and without binary plist). If so, I'll post. https://dl.dropboxusercontent.com/u/610494/outset_script-1.0.1.pkg

**Comment by erikng** [comment]
That is one awesome gif.

**Comment by erikng** [comment]
Should close this one :)
