### ISSUE TITLE
Feature Request: logouts

### ISSUE THREAD

**Issue by majorsl** [chilcote/outset#15]
With Login Hooks deprecated for awhile now, there isn't something (I can find) that easily lets us run a script at logout.

This seems a perfect fit for outset.  Would this be possible?

Additions might be in the outset folder:

logout-every
logout-once

**Comment by hunty1** [comment]
Although LoginHooks are deprecated, they still function correctly in 10.10 and el capitan so i wouldnt be too worried about it 

BUT

this should be easy(ish) to implement with another launchdaemon that simply waits for the correct sig from loginwindow when it logs out. Although it seems that this is only working on 10.10 despite the documentation suggesting that it should work on 10.9.  I haven't tested on 10.11 yet but i'll give it a crack a bit later on

eg.
```
#!/bin/sh
onLogout() {
    echo 'Logging out' >> ~/Logs/logout.sh.log
    exit
}

trap 'onLogout' SIGINT SIGHUP SIGTERM
while true; do
    sleep 86400 &
    wait $!
done
```

This link better explains it
http://apple.stackexchange.com/questions/148411/run-script-on-logout-without-use-of-logout-hook

**Comment by chilcote** [comment]
That's interesting.  I'm curious though, since I've never needed or used logout hooks, what sorts of things do you use those for?  Deleting user folders for labs? I'm wondering if there's a Better Way(tm)?

**Comment by majorsl** [comment]
You're spot on with the labs. We run a few dual boot (and probably soon, triple boot) labs on our campus. The main purpose of the logout hook is to trap a logoff or shutdown by the user and instead do a reboot.

We need to do a reboot because we use "Refind" (http://www.rodsbooks.com/refind/) to present the user their boot choice.

I've found the above code example and just can't get it to work using outset or a launchd daemon.

For now, I've reverted to a logout hook and it's flawless, but I'd like to future proof a little hence my request. :)

**Comment by aysiu** [comment]
hunty1's suggestion completely works in both Yosemite and El Capitan.

Would it be messy then to have a script that runs hunty1's code by in /usr/local/outset/login-every that then calls /usr/local/outset/outset --logout, which in turn would run every script in /usr/local/outset/logout-every?

**Comment by aysiu** [comment]
I just created a pull request with the logout option enabled. I'd love it if people could test it out from my fork... and if it's good, have it be pulled into chilcote's master.

**Comment by gregneagle** [comment]
logouthooks run as root.

Wouldn't a Outset-driven logout script run as the current user?

So such a script could not always replace the functionality of a logouthook script.

**Comment by chilcote** [comment]
Yep. I brought this up in the PR conversation (https://github.com/chilcote/outset/pull/35#issuecomment-190866961) and you can see the response there (@aysiu has a different version of this PR that wraps logouthooks rather than using a LaunchAgent).  I'm still unsure whether this is something to add to outset, but I'm keeping it open for discussion.

**Comment by aysiu** [comment]
I've written it two ways—the current pull request uses a Launch Agent that runs the script when killed (usually at logout, but the admins who use it must be aware of the possibility of it being run prematurely). I've also done an offshoot (Offset) that uses a logout hook.

I'm definitely curious as to what Greg and others think about using a logout hook (deprecated but definitely still works) vs. a launch agent (not deprecated but poses some risks, albeit low in practical use).

**Comment by gregneagle** [comment]
A significant problem with using a logouthook: there can be only one. If an admin who has already implemented a logouthook in their environment installs this "Offset", it will replace their logouthook, leading to unhappiness.

If you go this route, expect much confusion and dismay, unless the installer is very smart about detecting this situation.

**Comment by aysiu** [comment]
That's a good point. I guess the idea is that because the logout hook can run only one script, that's where the usefulness of putting logout scripts into Outset would come in.

One fairly easy (though intrusive still) way to remedy this functionally would be to read the current logout hook (if it exists), find the location of the current logout hook script, move it to /usr/local/outset/logout-every, and then replace the logout hook after the move.

**Comment by gregneagle** [comment]
But then you have to be careful during upgrade installs that you are not moving the previous Offset logouthook to /usr/local/outset/logout-every all Inception-like...

**Comment by aysiu** [comment]
Good point. I guess the logic would be something like this:
1. See if there is a logout hook
2. See if it points to the Outset logout hook
3A. If it doesn't, move the script to /usr/local/outset/logout-every
3B. Replace the logout hook with Outset's own

**Comment by chilcote** [comment]
I think we should avoid LogoutHooks since other management tools that may be used in conjunction with Outset might conflict.  

For example, JAMF uses LogoutHooks for its Logout Policies:

```
$ sudo defaults read com.apple.loginwindow LoginHook
/Library/Application Support/JAMF/ManagementFrameworkScripts/loginhook.sh
```

**Comment by aysiu** [comment]
Good point. Even if we ran a script to throw JAMF's logouthook.sh into /usr/local/outset/logout-every/, there may be certain other things looking for that logouthook to exist where it is. You could always symlink it, but then it starts to get very messy.

**Comment by gregneagle** [comment]
More importantly, future upgrade installs (or reinstalls) of the JAMF tools would almost certainly reinstall JAMF's logouthook in place of Offset's.

Third-party vendors were _never_ supposed to use the login and logouthook mechanisms. I guess JAMF (among others) didn't get the message.

All the more reason for Outset/Offset to avoid them.

**Comment by chilcote** [comment]
I'm not feeling it.  Let's wait until Apple has a viable replacement for logouthooks.
