### ISSUE TITLE
Packages should not need to be executable

### ISSUE THREAD

**Issue by chilcote** [chilcote/outset#16]
Leaving this here for tracking. Issue reported by Anthony Reimer (http://www.ucalgary.ca/iaml/help/pro/outset-10104).  Problem is that if you drop a pkg into firstboot-packages, outset won't install it if it is not set to be executable (o+x). Need to change to relieve that requirement.

**Comment by arubdesu** [comment]
was the idea to `chmod +x` the script to correct, checking for file extension or something? It probably doesn't even need to be executable for others when it's firstboot, only root should be dealing with that...
