### ISSUE TITLE
Login Once

### ISSUE THREAD

**Issue by WardsParadox** [chilcote/outset#22]
Errors out
Traceback (most recent call last):
  File "/usr/local/outset/outset", line 262, in <module>
    main()
  File "/usr/local/outset/outset", line 256, in main
    process_items(login_once_dir, once=True)
  File "/usr/local/outset/outset", line 217, in process_items
    d = FoundationPlist.readPlist(run_once_plist)
NameError: global name 'run_once_plist' is not defined

Is this from something I am causing? I am just trying to deploy a script that sets up user docks via nmcspadden's outset dock profiler

**Comment by arubdesu** [comment]
I can't help but think we ran into this recently because someone was trying to run the `--login` option as root?

**Comment by WardsParadox** [comment]
And idiot of the day goes to...me.
​Makes a ton of sense now. ​
