### ISSUE TITLE
Python script error causes Outset to not finish every-boot

### ISSUE THREAD

**Issue by erikng** [chilcote/outset#24]
I found an interesting "issue" when upgrading to Outset 1.1 (and perhaps 10.10.5 with the new python).

One of my every-boot scripts had a coding issue and was giving a traceback. Outset immediately stopped and was not applying any subsequent scripts.

I'm not sure what can be done, but perhaps Outset should have some protection, allowing it to continue to run. This could be dangerous for obvious reasons, but I figured I would describe the issue and let you decide on the right action.

**Comment by chilcote** [comment]
Hm. It's supposed to trap script errors but continue... can you gist an example of a script that will break it?

**Comment by erikng** [comment]
https://github.com/nmcspadden/SetupAssistantProfiler/tree/c9927f1303001b4bf7fa72587ee98a44cc56c7c4

This specific commit.

**Comment by chilcote** [comment]
I can't replicate this.   The script you provided actually succeeds when invoked by launchd because `usr/bin/profiles` is being seen as a valid path (it's run from / I suppose).  However, even if I change that cmd to `sr/bin/profiles` it still moves along and runs the next script in the list.

```
foo:~ vagrant$ cat /var/log/outset.log 
09/21/2015 12:37:36 PM - INFO: Processing /usr/local/outset/everyboot-scripts/aaa_truck_rental.py
09/21/2015 12:37:36 PM - ERROR: Failure processing /usr/local/outset/everyboot-scripts/aaa_truck_rental.py: Traceback (most recent call last):
  File "/usr/local/outset/everyboot-scripts/aaa_truck_rental.py", line 33, in <module>
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 709, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1326, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

09/21/2015 12:37:36 PM - INFO: Processing /usr/local/outset/everyboot-scripts/configure_network_adapters.sh
09/21/2015 12:37:36 PM - INFO: boot processing complete
```

**Comment by erikng** [comment]
Since I fixed this on my end and you can't replicate. I am going to close this.
