### ISSUE TITLE
missing info in README.md about on-demand function

### ISSUE THREAD

**Issue by henningkessler** [chilcote/outset#28]
Hello chilcote,

outset is a really awesome tool, thanks a lot for your work. I just started to play with the on-demand function but I could not get it to work. After browsing the old issues I found a threat that mentions that you have to create the file /private/tmp/.com.github.outset.ondemand.launchd in order to activate it. As far as I can see there is no hint in Readme.md about this. 

As it is not a big deal to create this file with a post install script is there any reason not use the WatchPath key in the LaunchAgent?

**Comment by erikng** [comment]
You are right that it's not in the readme. I was going to issue a PR for adding that, but I'm currently in git purgatory. 

The watch path is how touching that file will invoke it.

**Comment by henningkessler** [comment]
I might be completely wrong but if you would use something like:
``
     <key>WatchPath</key>
     <dict>
       <key>/usr/local/outset/on-demand</key>
       <true/>
     </dict>
```
instead of
```
     <key>PathState</key>
     <dict>
       <key>/private/tmp/.com.github.outset.ondemand.launchd</key>
       <true/>
     </dict>
```
the creation of the /private/tmp/.com.github.outset.ondemand.launchd file would not be necessary anymore.

**Comment by chilcote** [comment]
Hm. QueueDirectories might work.  I'll test that.

**Comment by chilcote** [comment]
Seems to work.  That would be great, as to not have to rely on touching a file.  Can you try this branch? https://github.com/chilcote/outset/tree/watchpath

**Comment by erikng** [comment]
Devils advocate here. 

What if I want to stage a couple of scripts and not have them trigger until an event?

**Comment by chilcote** [comment]
What's "an event"?

**Comment by erikng** [comment]
Package installs and includes an on-demand script but should wait until the entire package is installed (say as a post install). With this method it would immediately run.

**Comment by chilcote** [comment]
Pretend I'm an idiot (should be easy!).  Can you give a full example?  I'm still not following. 

I guess the two behaviors would be:

1. Build up on-demand script(s), and only run them with a file trigger at a specific time.
2. Trigger immediately upon the script(s) being placed in the folder.

With the former, admins will have to follow somewhat opaque instructions to create a postinstall to touch the trigger file.  The latter seems easier from a documentation or user experience standpoint. 

However, I still don't really have a use case in mind for on demand scripts, so I'm open to suggestions.

**Comment by henningkessler** [comment]
I have tried the branch but there seams to be an issue with the LaunchAgent:
```
09.01.16 00:57:34,017 com.apple.xpc.launchd[1]: (com.github.outset.on-demand[11123]) Service exited with abnormal code: 1
09.01.16 00:57:34,017 com.apple.xpc.launchd[1]: (com.github.outset.on-demand) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
```

**Comment by erikng** [comment]
Did you try the prerelease package?

Also, we took the launch agent change to a vote and it was unanimously decided to keep the current configuration via touching a file. 

With that said, there was only one vote - two if you count Chilcote's non committal.

**Comment by chilcote** [comment]
Consensus is to keep the trigger file.  Erik convinced me with an example use case.  I think it's best to give the power to the admin over when the on-demand script(s) are triggered.
