### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by grahamgilbert** [chilcote/outset#29]
Since the latest version breaks previous configurations, would it be possible for this to be redesigned version 2? This makes it a bit easier to target different versions (if less than v2, use this directory).

**Comment by chilcote** [comment]
Took me a bit to understand what you're getting at. Read up on  "Semantic versioning."  Would you need a --version option too?

**Comment by grahamgilbert** [comment]
Would help, but I've already written a fact to pull that out. 

Sent from my iPhone




On Mon, Jan 11, 2016 at 9:46 AM -0800, "Joseph Chilcote" <notifications@github.com> wrote:












Took me a bit to understand what you're getting at. Read up on  "Semantic versioning."  Would you need a --version option too?
