### ISSUE TITLE
she-bang should be #!/usr/bin/python

### ISSUE THREAD

**Issue by aysiu** [chilcote/outset#34]
I had trouble running Outset, and Greg Neagle (via the MacEnterprise mailing list) was able to diagnose the issue.

When I ran the **/usr/local/outset/outset --login** script as is (with _#!/usr/bin/env python)_, I got this error message back:

```
Traceback (most recent call last):
File "/usr/local/outset/outset", line 28, in <module>
  import FoundationPlist
File "/usr/local/outset/FoundationPlist/__init__.py", line 1, in
<module>
  from FoundationPlist import *
File "/usr/local/outset/FoundationPlist/FoundationPlist.py", line 44, in
<module>
  from Foundation import NSData, \
ImportError: No module named Foundation
```

Greg suggested I change it to _#!/usr/bin/python_, and that did indeed fix the issue. For people with a custom python installation (or even not) that may be better.

**Comment by clburlison** [comment]
This was actually resolved with commit https://github.com/chilcote/outset/commit/159f00d6ec878b934e4b96a73a3b5d75c4da7f27 however a public release has not been made yet. I'm sure Joe would love people to test the current master branch if you have the time.

**Comment by aysiu** [comment]
I'll see what I can do. I can definitely attest to the #!/usr/bin/python piece working for now!

**Comment by chilcote** [comment]
Ironically, I used the original shebang by looking at existing projects like https://github.com/munki/munki/blob/master/code/client/makecatalogs#L1 not really knowing what it meant.
