### ISSUE TITLE
"Often" behaviour?

### ISSUE THREAD

**Issue by cgerke** [chilcote/outset#38]
Have you thought about adding daemons/agents that run on an interval? 
https://github.com/cgerke/outset

**Comment by chilcote** [comment]
Not really, no. Trying to avoid feature creep as much as possible. Can you provide a use case or three?

**Comment by cgerke** [comment]
Policy enforcement for people that dislike mcx and .mobileconfigs.

https://github.com/cgerke/outset/blob/master/custom-outset/pkgroot/usr/local/outset/often-system/often-system_example.py

https://github.com/cgerke/outset/blob/master/custom-outset/pkgroot/usr/local/outset/often-system/often-system_example2.py

https://github.com/cgerke/outset/blob/master/custom-outset/pkgroot/usr/local/outset/often-user/often-user_example.py

**Comment by cgerke** [comment]
It's cool, ignore this.

**Comment by chilcote** [comment]
I'm planning to look at these commits this week.

**Comment by cgerke** [comment]
OK np, I've just updated my plists to fix an issue in case you've already looked at it.

**Comment by chilcote** [comment]
Thanks @cgerke I'll try to block off some time tomorrow. Cheers.

**Comment by cgerke** [comment]
If you don't want to add more launchdaemons to this option, you could maybe alter the existing com.github.outset.boot.plist slightly so that it actually runs on an interval as well as boot, then the logic of outset simply skips everything except the often folder. A little like this idea I am playing with.

https://github.com/cgerke/flint

**Comment by rodchristiansen** [comment]
Hi @cgerke, I am using outset as it is for a similar behaviour of your remote management and remote login examples, but as `boot-every`. 

Added to the wiki here: https://github.com/chilcote/outset/wiki/AdminRemoteControl

**Comment by cgerke** [comment]
Yes this is a boot-every, not an interval-every, correct?

**Comment by chilcote** [comment]
Closing this issue since I completely neglected to look at the examples before they disappeared.
