### ISSUE TITLE
Created pull request for outset to be installable via homebrew cask

### ISSUE THREAD

**Issue by ryanmoon** [chilcote/outset#40]
Opened a pull request:
https://github.com/caskroom/homebrew-cask/pull/24306

**Comment by chilcote** [comment]
Do I need to do anything or is this informational only? Can you add something to the wiki, please?

**Comment by ryanmoon** [comment]
Informational.

I'll add it to the section on installing outset.

**Comment by chilcote** [comment]
Right on, thanks.
