### ISSUE TITLE
Feature Request: recurse Outset directories

### ISSUE THREAD

**Issue by orbsmiv** [chilcote/outset#41]
Have you considered using e.g. `os.path.walk` instead of `os.listdir` in the _process_items_ function? For organisation of the scripts, particularly those which run regularly, it would be helpful if Outset could recurse subdirectories so that, for example, all scripts relating to a given application could be collated.

**Comment by chilcote** [comment]
Sounds good to me.  I'll put something together soon.

**Comment by chilcote** [comment]
Please try https://github.com/chilcote/outset/tree/recursive_walk and let me know if that does what you expect.

**Comment by orbsmiv** [comment]
Implementation looks good although I'm on leave until Friday so not in a position to check on work's systems. One small (possibly inaccurate!) observation... is `os.path.join` in line 250 now unnecessary given that the walk produces absolute paths?

**Comment by chilcote** [comment]
Nope I think you are correct.  Nice catch.  I updated the branch.

**Comment by orbsmiv** [comment]
Finally managed to test this and it works great, thanks!

**Comment by chilcote** [comment]
Right on, thank you.
