### ISSUE TITLE
Login Scripts fail to run condition

### ISSUE THREAD

**Issue by franton** [chilcote/outset#42]
Hi,

I've been playing around with altering the default folder locations inside outset. What i've found is if you direct the outset logging for login once and login every to a folder that doesn't exist, none of those scripts actually run. Confirmed by changing the user log folder path to a known good location and having things work as expected.

Not a showstopper by any means.

**Comment by franton** [comment]
I'm altering the paths in the script directly.

**Comment by chilcote** [comment]
Ah OK.  This issue can work as a reference for others who want to change the default log directories.  Thanks!
