### ISSUE TITLE
Error when running outset manually from command line

### ISSUE THREAD

**Issue by damacguy** [chilcote/outset#46]
Not sure if it's something i'm doing...
`bash-3.2# sudo ./outset --login`
`Traceback (most recent call last):`
`   File "./outset", line 483, in <module>`
`     main()`
`   File "./outset", line 388, in main`
`     process_items(login_once_dir, once=True, override=override_login_once)`
`   File "./outset", line 262, in process_items`
`     d = FoundationPlist.readPlist(run_once_plist)`
` NameError: global name 'run_once_plist' is not defined`

**Comment by erikng** [comment]
You can't run outset as root with the --login flag.

**Comment by damacguy** [comment]
D'oh... makes total sense and I read that earlier too. ID10T error.
