### ISSUE TITLE
directory listings should be sorted

### ISSUE THREAD

**Issue by dhmoore** [chilcote/outset#48]
In testing High Sierra on APFS, I found that my outset login-once scripts did not run in alphabetical order. I tested os.listdir in the system's Python 2.7 and other directory listings were in random order, too.

At first I thought this might be an OS bug, but the docs for os.listdir state that the listing is in arbitrary order.
https://docs.python.org/2/library/os.html

**Comment by chilcote** [comment]
Can you try the latest commit(s) in Hi-C please? 

https://github.com/chilcote/outset/commit/5188911e67d868660cbd5961cd34c18c257d7e3f

**Comment by dhmoore** [comment]
Filenames starting with numbers ran first in the correct order, then upper-case in alphabetical order, then lowercase in alphabetical order.

**Comment by arubdesu** [comment]
Yay, so it would seem [the docs](https://github.com/chilcote/outset/wiki/FAQ#what-order-do-jobs-run-in) are accurate on Hi-C now as well?

**Comment by dhmoore** [comment]
Doesn't look like it. The Q at that link says "a file starting with 000 will be evaluated before one that starts with 0a, after which would be files like aaa that start with lowercase characters, then capitalized files AAA." 

I found that upper-case-files ran before lower-case.

**Comment by chilcote** [comment]
That's true. It seems os.walk was doing things oddly even pre Hi-C.  I think the new way of sorting capitalized before lowercase is preferable, and is more in line with what I'd expect.  For example:
```
>>> l = ['001', '010', '002', 'aaa', 'AAAA', 'A101', 'A001', 'A002', 'a001', 'a100']
>>> print l
['001', '010', '002', 'aaa', 'AAAA', 'A101', 'A001', 'A002', 'a001', 'a100']
>>> l.sort()
>>> print l
['001', '002', '010', 'A001', 'A002', 'A101', 'AAAA', 'a001', 'a100', 'aaa']
```
What say we update the docs to reflect the new correct behavior?

**Comment by dhmoore** [comment]
Your call, but I would worry that some people depend on the documented order. Also, for documentation, you might want to specify how Outset's behavior relates to other ways of viewing file listings. The new behavior matches the way ls sorts, but Finder listings are case-insensitive (at least for non-case-sensitive HFS+).

**Comment by erikng** [comment]
I think it should be expected that file directory listings are going to be changing for 10.13 and people should expect these changes.

If they are blindly updating outset to their fleet and not testing, the onus is on them.

Thanks,
Erik Gomez
________________________________

**Comment by chilcote** [comment]
Agreed

**Comment by pixelrebel** [comment]
While scripts may execute in order, they only do so in their groups.  The following scripts:
```
/usr/local/outset/login-privileged-once/10-privileged.sh
/usr/local/outset/login-once/20-unprivileged.sh
```
actually execute in the following order:
```
/usr/local/outset/login-once/20-unprivileged.sh
/usr/local/outset/login-privileged-once/10-privileged.sh
```

How do I get `login-privileged-once` scripts to execute before `login-once` scripts?

**Comment by chilcote** [comment]
You'll want to change the order here https://github.com/chilcote/outset/blob/master/pkgroot/usr/local/outset/outset#L423-L428
