### ISSUE TITLE
Privileged directories?

### ISSUE THREAD

**Issue by stevemillermac** [chilcote/outset#50]
If the other directories are being created on install, why not include the privileged ones also?

/usr/local/outset/login-privileged-once/
/usr/local/outset/login-privileged-every/

**Comment by chilcote** [comment]
on install, or on update?

On install, the launchdaemons are loaded, and this runs which will create the dirs:
https://github.com/chilcote/outset/blob/master/pkgroot/usr/local/outset/outset#L382-L394

On update, I'm not positive the launchdaemons are being re-loaded.  At next boot those directories should be created.

However, they're only really needed if they contain scripts, and the pkg to install those scripts should also be creating those directories, right?

Is this causing a failure?

**Comment by stevemillermac** [comment]
Yeah, looks like _outset --boot_ after pkg install will accomplish creating them. 

Just seems odd that the following are all created during install, but the privileged are created on next reboot or with the --boot command. Nothing in the wiki calls out privileged directories being created after next reboot. Thanks for the clarification.

/usr/local/outset/boot-every/
/usr/local/outset/boot-once/
/usr/local/outset/login-every/
/usr/local/outset/login-once/
/usr/local/outset/on-demand/

**Comment by chilcote** [comment]
No, sorry for not being more clear. These directories should be created at install.  But are you _installing_ or are you _upgrading from an earlier version_? Behavior may be different for the latter, because the launchdaemon is already loaded.

**Comment by stevemillermac** [comment]
Tested this morning and yes, they are working as you suggested above. Since we upgraded from .03 to 06, just adding the --boot command after the upgrades saves my users from the reboot and allows the next stage up pushing into privileged folders. Thank you

**Comment by chilcote** [comment]
Glad it's working now.  Before closing this issue, I'm curious, what does "allows the next stage up pushing into privileged folders" mean? I'm trying to understand where this is becoming a problem. If you are installing scripts into one of those directories, the directories are being created as a result, no?

**Comment by stevemillermac** [comment]
I'm working to solve an issue that our MDM seems to suck at, Login triggers. Outset has been great for other things but having to update from 2.0.3 to 2.0.6 to get privileged login work. While testing I didn't see the privileged folders being created. Didn't see anything in the docs about the update needing a reboot and didn't dive into the code itself for the answer. Would a package make the folders, yes. I think a line about upgrades from previous version in the wiki will make things clear. Thank you for the great tool also!

**Comment by chilcote** [comment]
Good idea about the wiki. One more quick question and I'll leave you alone :)

How were you putting scripts in the login-privileged folders? Copying them with another script?

**Comment by stevemillermac** [comment]
In my test box, create and test the scripts in the login-privileged folder. When happy with result, use Composer to make pkg.

**Comment by chilcote** [comment]
Ah OK I see. That makes sense. Thanks for the explanation. I'll go ahead and close this one out.
