### ISSUE TITLE
Wiki says to test login script with /usr/local/outset --login but that creates problem with login-privileged script

### ISSUE THREAD

**Issue by vikaskedia** [chilcote/outset#56]
Over here at the wiki:
https://github.com/chilcote/outset/wiki#overview

It says:
![image](https://user-images.githubusercontent.com/6703876/34595506-64117e58-f18d-11e7-82b4-0bbb9b2ee262.png)

When I invoke it with:
/usr/local/outset/outset --login
 
it executes the login-privileged scripts, but it does not have the privilege.

I am confused how will it execute the login-privileged scripts?

**Comment by chilcote** [comment]
When you run `/usr/local/outset/outset --login` it touches a trigger file, here:
https://github.com/chilcote/outset/blob/master/pkgroot/usr/local/outset/outset#L428

This trigger file invokes a LaunchDaemon which runs in the root context, via this PathState:
https://github.com/chilcote/outset/blob/master/pkgroot/Library/LaunchDaemons/com.github.outset.login-privileged.plist#L14-L17

Which kicks off a privileged run of `/usr/local/outset/outset --login-privileged` via the same LaunchDaemon:
https://github.com/chilcote/outset/blob/master/pkgroot/Library/LaunchDaemons/com.github.outset.login-privileged.plist#L7-L11

Which runs this part of outset with root privs:
https://github.com/chilcote/outset/blob/master/pkgroot/usr/local/outset/outset#L432-L442

Hope that helps.

**Comment by vikaskedia** [comment]
Thanks.

Its a very elegant piece of code. Well done!!
