### ISSUE TITLE
Scripts run manually, but not on boot

### ISSUE THREAD

**Issue by atrystan** [chilcote/outset#58]
The Jamf forum and many Google searches pointed us towards you. We are trying to create a simple script that unmounts a particular partition, either on boot or at login, so that it remains relatively hidden from our users.

Our script will contain the following:

`umount /Volumes/admin
`

Nothing really special here. If we invoke it manually by doing:

`/usr/local/outset/outset --login
`

it works just fine. It does not seem to work on login, however. Could you suggest where we might begin to troubleshoot?

**Comment by WardsParadox** [comment]
Would you post the script?

**Comment by ndavis98uw** [comment]
Hi, I've also been working on this issue with atrystan. Here is the script that we've been using.

[unmount_admin.txt](https://github.com/chilcote/outset/files/2233742/unmount_admin.txt)

**Comment by WardsParadox** [comment]
Your script is using `sudo`. There are no prompts presented when launched via a LaunchAgent/Daemon so it fails. Try doing:
```
#!/bin/bash
umount /dev/disk0s4
```
and store it in `login-every-privilaged` instead. that should execute it at login with admin privilages.

**Comment by atrystan** [comment]
Hadn't realized that there was a sudo in there. Putting it in the privileged folder seems to have taken care of it. Cheers!
