### ISSUE TITLE
Feature Suggestion: Script Triggered When All Items Processed?

### ISSUE THREAD

**Issue by gsmc-alx** [chilcote/outset#62]
How about adding the ability to run a script when all startup/login etc. items have been processed?

This would facilitate implementation of eg a script to check is all items have been successfully processed/pkgs installed etc.

**Comment by chilcote** [comment]
I'm not sure what this solves? If the scripts aren't working, then this meta-script wouldn't work either, right?

**Comment by gsmc-alx** [comment]
It depends what you mean by "not working". Sometimes it's useful to know if all scripts have executed.

I guess there are other ways to achieve this though.

I've taking to adding  numeric prefixes to my outset scripts, to force them to execute in a particular order.

**Comment by chilcote** [comment]
> It depends what you mean by "not working".

I mean, I wouldn't trust a script to check if all the other scripts are working, if there's  a chance that the script(s) aren't working.

I would tend to rely on the logging for this data. Is there something missing in the logging?

**Comment by gsmc-alx** [comment]
> I would tend to rely on the logging for this data. Is there something missing in the logging?

No, I think it's fine. You've convinced me it's not a good idea :)
