### ISSUE TITLE
Network timeout not working correctly on first boot

### ISSUE THREAD

**Issue by zackbennis** [chilcote/outset#63]
I'm trying to use outset to bootstrap new Macs, and running into an issue where the network timeout function incorrectly identifies one of the virtual interfaces (specifically awdl0) as having a valid ip address (albeit inet6), and therefore continues on with the scripts, which proceed to all fail, since there is no valid network connection.

Seems like this could be mitigated in the outset network_up function (line 76) by exempting the 'fake' interfaces from being considered during the network timeout function.

**Comment by chilcote** [comment]
IPV6 is not a consideration made in the code. Maybe it would be worthwhile adding a boot_every script called `AAAIgnoreNICs.sh` and add your logic there? The problem I see here is with unilaterally deciding what is a "fake" interface, and what is valid.

**Comment by zackbennis** [comment]
Presumably any script I add to boot_every won't fix this issue, since the script will just wait for the network_up function to return a true before continuing, and returning 'true' too early is the issue I'm running into. I could be getting the logic wrong, though.

The problem is two-fold for me: 1. outset is continuing to the login screen before all the scripts run, and 2. I don't seem to be getting a network connection at the login window. A few of my scripts are network dependent, for example, binding to AD.

**Comment by chilcote** [comment]
[Disable outset's wait for network](https://github.com/chilcote/outset/wiki/NetworkTimeout#removing-the-network-timeout-requirement) and use your own custom method via a script that runs first due to its alphanumeric nature. I.e. "AAAfoo.sh"
