### ISSUE TITLE
Bad Permissions error when running any script.

### ISSUE THREAD

**Issue by B-Whittaker** [chilcote/outset#64]
Been trying to get this working for a while now and cant think of what might be causing this.

I have tried multiple scripts, that when run in terminal separately from outset, work without any issues. The main 2 I have been using as tests have been .sh and .py files with chmod +x checked on both (777).  

when manually invoked through outset using --login-every it provides the error 'Bad Permissions'.
![outset-bad-perms](https://user-images.githubusercontent.com/47011665/51742367-7530f400-2091-11e9-9ec0-a863a74f1127.png)

I have tried them with login-privileged-every and it provides the same results. I have tried it with 2 different Macbooks, one on Mojave and the other High-Sierra.  Also tried using sudo to elevate the manual execution through outset and this didn't work either. 

This is what's contained in the SafariSettings1.sh file if that helps?
![image](https://user-images.githubusercontent.com/47011665/51743793-b2978080-2095-11e9-9f9f-9acad3689a06.png)

**Comment by vmiller** [comment]
You scripts should have the ownership set to root and the mode set to 755.

**Comment by B-Whittaker** [comment]
Can't believe I missed that! Thanks a million :)
