### ISSUE TITLE
[Errno 8] Exec format error

### ISSUE THREAD

**Issue by yao89** [chilcote/outset#65]
Hey,

I got a problem for a simple usage of your cool app.
We are a high school, with multiple computers (250+ macOS), and a lot of students, who logged on computers with AD authentification.

I just want that a app a created with Nativier open a login on some computers.

So i discover your app, and try it.
I've copy my script in /usr/local/outset/login-every and /usr/local/outset/login-privileged-every.
Here is the script

>#!/bin/sh
> #Ouverture de Support IT.app
> open /Applications/Support\ IT.app
> exit 0

Permission of this one is
`-rwxr-xr-x@ 1 root wheel 162 14 mar 12:33 login_hook-support_it.sh`

And here is the error when i type "/usr/local/outset/outset --login"
`Failure processing /usr/local/outset/login-every/login_hook-support_it.sh: [Errno 8] Exec format error`
Same in log file.

It seems that my script is'nt in good format, but don't understand why, and what to do...
I've try to change "#!/bin/sh" to "#!/bin/bash" but nothing change.

Thanks a lot in advance.

**Comment by vmiller** [comment]
I have no problems opening an app with a login-every script, but I have no experience with Nativier.

What happens if you run `/usr/local/outset/login-every/login_hook-support_it.sh` directly?

**Comment by yao89** [comment]
Hey, thanks for your help. Finally, I success with launchctl.

Thanks ;)
