### ISSUE TITLE
v.3.0.0 Release documentation incorrect, dead link

### ISSUE THREAD

**Issue by jazzace** [chilcote/outset#69]
The [release notes posted with 3.0.0](https://github.com/chilcote/outset/releases/tag/3.0.0) have a couple of issues.

> By default, it's still set to use /usr/bin/python which is Apple's system python2.

The main outset script uses `/usr/bin/env python3` in this release. Users would need to alter it to use Python2. 

Also, the link to the main outset script reflects the development fork and as such returns a 404 error. The correct link is https://github.com/chilcote/outset/blob/master/pkgroot/usr/local/outset/outset#L1

**Comment by chilcote** [comment]
updated the release notes, thanks for pointing that out.

> Also, the link to the main outset script reflects the development fork and as such returns a 404 error. The correct link is https://github.com/chilcote/outset/blob/master/pkgroot/usr/local/outset/outset#L1

Where is this?
