### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by grahamgilbert** [chilcote/outset#7]
It would be useful from an automation point of view (AutoPkg) and would help new users if there was a pre build package in the releases section.

**Comment by chilcote** [comment]
Good idea, I'll work on it.

**Comment by chilcote** [comment]
OK I think I clicked all the right buttons to add a pkg to the v1.0.0 release.

**Comment by grahamgilbert** [comment]
Awesome, I already have a autopkg recipe up. One minor suggestion though - make the package version the same as the release version. In the Makefile:

```
PACKAGE_VERSION=1.0.0
```

**Comment by chilcote** [comment]
Thanks, and done.
