### ISSUE TITLE
Login-privileged-once not executing Catalina

### ISSUE THREAD

**Issue by lpglycerine** [chilcote/outset#71]
Having an issue with the _login-privileged-once_ folder on Catalina. The scripts in this folder only execute on the first boot of the first user created on the computer, but are not executing for any new user accounts after that. There is no indication in /var/log/outset.log that the _login-privilege-once_ scripts even try to run for new users.

Additional Notes:
- _Login-privileged-every_ scripts are executing correctly for all users

**Comment by lpglycerine** [comment]
After further investigation, there is only one _com.github.outset.once.0.plist_ file being created and used for all users. After all the files in _login-privileged-once_ execute on the initial boot-up, the filenames are stored in _com.github.outset.once.0.plist_. All subsequent users look at this same file and see that the scripts have already ran once so they do not execute. If this file is deleted then the scripts will execute for another user.

**Comment by pixelrebel** [comment]
It seems the [current approach for finding the current uid](https://github.com/chilcote/outset/blob/master/pkgroot/usr/local/outset/outset#L64) results in 0 in Catalina.  

@lpglycerine has a fix incomming.

**Comment by lpglycerine** [comment]
console_uid was being set to 0 for all users, whereas in outset 2.0.6 this value was defined differently and was the unique UID for the current console user.

So I changed console_uid to be defined via a different method; os.stat('/dev/console').st_uid
Tested compatibility on 10.8.5, 10.10.5, 10.11.6, 10.13.6, 10.14.5 and 10.15.2

Now each user gets a unique plist which determines if the once scripts have ran for that user or not. [https://github.com/chilcote/outset/pull/72](url)

**Comment by chilcote** [comment]
Interesting and nice catch! Thank you for putting up a fix :)
