### ISSUE TITLE
permissions issue on launchagents and daemons Catalina 10.15.7

### ISSUE THREAD

**Issue by dnsBlah** [chilcote/outset#77]
Hi all,

I've been working on getting outset ready for deploy.
I don't know if it affects older OSX versions as well ( older than 10.15.6 at least, I just updated a moment ago )

The ownership of the files are fine ( root : wheel )
But the permissions aren't. They currently they are: -rw-r--r--
Resulting in an error: /Library/LaunchDaemons/com.github.outset.boot.plist: Path had bad ownership/permissions when trying to load the launchctl
But should be -rw------- ( chmod 600 )
After changing it it worked straight away.

Adjusting the Postinstall to set the permissions before loading them

I will test it out on a Mojave machine later when I finished all my packaging

**Comment by vmiller** [comment]
All the Launch Daemons on my 10.15.7 system are 644 and I haven't noticed any problem.  Can you provide more details on how to duplicate the problem you are seeing?

I'll admit I haven't ever had the need to manually load the outset daemons/agents.

**Comment by chilcote** [comment]
> should be -rw------- ( chmod 600 )

I don't think that's true. Even the system launchdaemons are 0644. for example:
```
-rw-r--r--  1 root  wheel  1034 Jan  1  2020 /System/Library/LaunchDaemons/ssh.plist
```
