### ISSUE TITLE
Outset 3.0.0/3.0.1 Error adding excluded users

### ISSUE THREAD

**Issue by gsmc-alx** [chilcote/outset#78]
I get the following error when attempting to add excluded users with the command
`/usr/local/outset/outset --add-ignored-user FOO`

```
Traceback (most recent call last):
  File "/usr/local/outset/outset", line 634, in <module>
    main()
  File "/usr/local/outset/outset", line 450, in main
    prefs = plistlib.readPlist(outset_preferences)
AttributeError: module 'plistlib' has no attribute 'readPlist'
```

MacOS 10.15.7
I have Python3 installed from the Developer Tools.

**Comment by gsmc-alx** [comment]
Possibly related to this note, from the plistlib docs for Python 3.8.6?

> Deprecated since version 3.4: Use load() instead.
> 
> Changed in version 3.7: Dict values in the result are now normal dicts. You no longer can use attribute access to access items of these dictionaries.

https://docs.python.org/3.8/library/plistlib.html#plistlib.load

**Comment by gsmc-alx** [comment]
plistlib.writePlist has also been removed from Python 3.9.

**Comment by chilcote** [comment]
Thanks, can you try the change in https://github.com/chilcote/outset/tree/plistlib and see if that fixes it for you?

**Comment by gsmc-alx** [comment]
Hi, that was quick!

Sadly that doesn't work. I now get this error, when trying to add an ignored user:

> Traceback (most recent call last):
>   File "/usr/local/outset/outset", line 634, in <module>
>     main()
>   File "/usr/local/outset/outset", line 450, in main
>     prefs = plistlib.load(outset_preferences)
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/plistlib.py", line 840, in load
>     header = fp.read(32)
> AttributeError: 'str' object has no attribute 'read'

I don't know any Python, but did manage to hack together a test script to read from the Outset prefs file, using the plistlib docs.

I don't have it to hand right now, but from memory, I think I had to open the file first, (presumably into RAM), then load that.

Something like:

```
with open(outset_preferences, 'rb') as fp:
    prefs = plistlib.load(p)
```

I didn't get round to attempting to fix the writing back to the plist.

**Comment by gsmc-alx** [comment]
That seems to work :)

**Comment by gsmc-alx** [comment]
Forked and fixed here:
https://github.com/gsmc-alx/outset

**Comment by chilcote** [comment]
I'm happy to take a PR for that if you want, or I can update the branch I have. Then if it all works out, I can cut a new release.

**Comment by gsmc-alx** [comment]
I issues a pull-request. I hope I did it right. I'm not a big GitHub user, so I may have done it wrong.

**Comment by gsmc-alx** [comment]
Seems to be!

**Comment by chilcote** [comment]
Thanks. After Allister is done fixing everything else I'll cut a new pkg :)
